---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: promethus
    repoURL: https://github.com/emiresh/ArgoCD.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true